services:
  - type: web
    name: tienda-web
    env: java
    plan: free
    buildCommand: "mvn -q -DskipTests package"
    startCommand: "java -jar target/tienda-web-1.0.0.jar"
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 8080
